Imports

In [4]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Configuration du device
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device utilisé : {DEVICE}")

Device utilisé : cuda


In [7]:
data = [1,2,3,4,5,6,7,8,9]
tensor = torch.tensor(data)
print(tensor)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [14]:
data_2d = [[1, 2, 3], [4, 5, 6] ]
tensor_2d = torch.tensor(data_2d, dtype=torch.int64)
print(tensor_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
# redimention de tensors

tensor = torch.randn(4, 4)
nouveau_tensor = tensor.view(16)
print(tensor.shape) # torch.Size([4, 4])
print(tensor)
print(nouveau_tensor.shape) # torch.Size([16])
print(nouveau_tensor)

torch.Size([4, 4])
tensor([[-0.2324,  1.3426, -1.4837,  0.2887],
        [ 1.0633,  0.9784, -0.4853, -0.7415],
        [ 0.5869, -1.6901,  0.9751, -0.2866],
        [-0.5582, -1.5562, -1.2381,  0.6579]])
torch.Size([16])
tensor([-0.2324,  1.3426, -1.4837,  0.2887,  1.0633,  0.9784, -0.4853, -0.7415,
         0.5869, -1.6901,  0.9751, -0.2866, -0.5582, -1.5562, -1.2381,  0.6579])


In [21]:
tensor = torch.randn(2, 3, 4)
print(tensor)
nouveau_tensor = tensor.reshape(4, -1)
print(nouveau_tensor)
print(tensor.shape) # torch.Size([2, 3, 4])
print(nouveau_tensor.shape) # torch.Size([6, 4]))


tensor([[[ 0.2477, -0.8267, -1.1174, -1.1064],
         [-0.4661,  1.1431,  1.4816,  0.4534],
         [ 0.9066,  0.0704, -0.5906,  1.1792]],

        [[-0.6988,  0.3190,  0.6658, -0.0843],
         [-1.1540,  0.8358, -0.7547,  0.5968],
         [ 0.8152, -0.0064, -0.0867, -1.1944]]])
tensor([[ 0.2477, -0.8267, -1.1174, -1.1064, -0.4661,  1.1431],
        [ 1.4816,  0.4534,  0.9066,  0.0704, -0.5906,  1.1792],
        [-0.6988,  0.3190,  0.6658, -0.0843, -1.1540,  0.8358],
        [-0.7547,  0.5968,  0.8152, -0.0064, -0.0867, -1.1944]])
torch.Size([2, 3, 4])
torch.Size([4, 6])
